---
# When changing options in this file, please also run:
#    python3 script/generate.py dev
# to update the dev addon config (beta/stable configs will be updated on next release by release script)
base: &base
  url: https://docs.libretuya.ml/docs/projects/esphome/
  arch:
    - amd64
  # Uses Home Assistant Supervisor API (auth)
  hassio_api: true
  auth_api: true
  # Host network mode for mDNS
  host_network: true
  # Ingress settings
  ingress: true
  ingress_port: 0
  panel_icon: 'mdi:chip'
  # Automatically add UART devices to add-on
  uart: false
  ports:
    '6052/tcp': null
  map:
    - ssl:ro
    - config:rw
  discovery:
    - esphome
  schema:
    status_use_ping: bool?
    streamer_mode: bool?
    home_assistant_dashboard_integration: bool?
    default_compile_process_limit: int(1,)?
    ssl: bool?
    certfile: str?
    keyfile: str?
    relative_url: str?
    leave_front_door_open: bool?
  backup_exclude:
    - "*/*/"
  # Disable docker init for s6
  init: false

esphome-stable:
  <<: *base
  directory: esphome
  name: LibreTuya ESPHome
  version: '20230214-25e1c49a'
  slug: libretuya-esphome
  description: "ESPHome add-on for intelligently managing all your Tuya devices"
  image: ghcr.io/palkovicm/libretuya-esphome-hassio

copy_files:
  CHANGELOG.md:
  DOCS.md:
  icon.png:
  logo.png:
  README.md:
  translations/en.yaml:
