---
url: https://docs.libretuya.ml/docs/projects/esphome/
arch:
- amd64
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: false
ports:
  6052/tcp: null
map:
- ssl:ro
- config:rw
discovery:
- esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  ssl: bool?
  certfile: str?
  keyfile: str?
  relative_url: str?
  leave_front_door_open: bool?
backup_exclude:
- '*/*/'
init: false
name: LibreTuya ESPHome
version: 20230214-25e1c49a
slug: libretuya-esphome
description: ESPHome add-on for intelligently managing all your Tuya devices
image: ghcr.io/palkovicm/libretuya-esphome-hassio
